ALTER TABLE teams ADD COLUMN IF NOT EXISTS skills text[];
ALTER TABLE teams ADD COLUMN IF NOT EXISTS required_expertise text[];
ALTER TABLE teams ADD COLUMN IF NOT EXISTS current_members_count INT NOT NULL DEFAULT 1;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS is_completed BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS stars_count INT NOT NULL DEFAULT 0;
